### ISSUE TITLE
Implement crypto channels / secio

### ISSUE THREAD

**Issue by folsen** [paritytech/rust-libp2p#11]
See: https://github.com/libp2p/go-libp2p-secio

**Comment by diasdavid** [comment]
And also this one https://github.com/libp2p/js-libp2p-secio

You will also need something like https://github.com/libp2p/js-libp2p-crypto

**Comment by diasdavid** [comment]
//cc @dignifiedquire to track this issue

**Comment by tomaka** [comment]
Done in #33
