### ISSUE TITLE
Small nitpick, could you rename to `rust-libp2p`

### ISSUE THREAD

**Issue by diasdavid** [paritytech/rust-libp2p#32]
Just to follow all the name convention used by all the other rust pieces we have :)

**Comment by folsen** [comment]
Yup! It's still unclear where/how everything lives, but this is something i've had in mind as well. Calling things `-rs` is common Rust practice, but I agree fitting with the rest of the libraries is higher importance in this case, improves discoverability.

**Comment by diasdavid** [comment]
Thank you :)
