### ISSUE TITLE
Multiplex stream implementation

### ISSUE THREAD

**Issue by folsen** [paritytech/rust-libp2p#8]
Under the [stream muxer](3) interface.

See go implementation: https://github.com/whyrusleeping/go-smux-multiplex

**Comment by diasdavid** [comment]
You can also take inspiration from:
- http://github.com/libp2p/js-libp2p-multiplex
- https://github.com/libp2p/go-stream-muxer (go interface)
- https://github.com/libp2p/interface-stream-muxer spec + tests

**Comment by Vurich** [comment]
🎉
